### ISSUE TITLE
SMLM Test fit gives Printing of uicontrols errors

### ISSUE THREAD

**Issue by kalidke** [LidkeLab/smite#25]
File /usr/local/MATLAB/R2021a/toolbox/matlab/graphics/printing/private/validate.m, line 166, in validate

  File /usr/local/MATLAB/R2021a/toolbox/matlab/graphics/printing/print.m, line 67, in print

  File , line 0, in @(h,i)print(h,sprintf('/tmp/tmp50_9p7en/%06i',i),'-dpng','-r96')
Printing of uicontrols is not supported on this platform.

**Comment by MJWester** [comment]
This error was due to trying to display a sliceViewer in a JyputerHub MATLAB notebook.  The sliceViewer is now displayed only if TestFit is invoked and only if the TestFit has been called from the GUI or if SMLM.VerboseTest >= 5 (VerboseTest defaults to 3 currently), otherwise it is written as an mp4 and not displayed interactively.
