### ISSUE TITLE
JOSS Review : Submit Smite to EPFL SRM Hub

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/smite#40]
[Joss review](https://github.com/openjournals/joss-reviews/issues/5563) 
Optional but recommended suggestion, have your software (I couldn't find smite there) in the EPFL SRM Hub: https://srm.epfl.ch/SoftwareList

**Comment by MJWester** [comment]
Thank you for the suggestion.  We contacted

   daniel.sage@epfl.ch

who seems to be in charge of and contact for this website with subject:
"Pre-registration to Single-Molecule Localization Microscopy Challenge"
as directed by the EPFL website.  We are awaiting a response, although we
note that the above-mentioned list has not been updated since 2019, and
registration for the 3D software challenge (SMITE is a 2D code),
"is currently on hold and may resume shortly."

If I haven't heard from Daniel Sage when I am back from traveling (I'll be
gone until early August), I'll try contacting him again.

**Comment by bencardoen** [comment]
Thank you for the clarification, perhaps it'd be an idea for the community to host a global list of SMLM software (I know of other packages not listed as well). If you agree I could start a github gist/table.

**Comment by MJWester** [comment]
I wrote again to Daniel Sage and got this reply today:

Dear Michael,
Sorry for this late answer.

We are revamping the website srm.epfl.ch and moving on a new server as
requested by our security IT department. It takes more time than expected!

ASAP, we will inform when we will update our website, and for sure we will
include your software SMITE.

Best,

Daniel

**Comment by bencardoen** [comment]
@MJWester thank you for sharing this, I'll resend our emails on adding to EPFL's table, best to keep these things in 1 place.
