### ISSUE TITLE
Drift correction request

### ISSUE THREAD

**Issue by dschodt** [LidkeLab/smite#5]
I'm analyzing several not so great sets of data.  A lot of my data contains no localizations for, e.g., the first 15 out of 50 datasets, with the remaining datasets containing useful data that I need analyzed.  As a result, the following error is given by from line 172 of smi_core.DriftCorrection/driftCorrectKNNInter(): "First dataset is empty!  Cannot perform inter-dataset drift correction."

Is it possible to, for example, make driftCorrectKNNInter() search for and use the first non-empty dataset as the reference?

**Comment by MJWester** [comment]
David wrote smi_core.SingleMoleculeData.isolateSubSMD and smi_core.Driftcorrection.changeInterRef, which get around this issue, and then it turned out we had no further examples (it's a rare condition for super-resolution data).  Also, David write a brightfield (BF) drift correction that does not have this issue.
