### ISSUE TITLE
dipimage dependency in smi testfit

### ISSUE THREAD

**Issue by kalidke** [LidkeLab/smite#7]
Need to remove dipimage dependency from the boxplot.  

`SR.testFit(1)`

```
Unrecognized function or variable 'dipshow'.

Error in smi_core.FindROI.plotBox (line 26)
dipshow(Data(:,:,Frame))

Error in smi_core.FindROI/findROI (line 198)
                obj.plotBox(SMD, obj.Data, obj.PlotBoxFrame, obj.BoxSize);

Error in smi_core.LocalizeData/genLocalizations (line 30)
[ROIStack, SMDCandidates] = FindROI.findROI();

Error in smi.SMLM/analyzeDataset (line 218)
        [SMD] = LD.genLocalizations();

Error in smi.SMLM/analyzeAll (line 166)
            SMDnn = obj.analyzeDataset(DatasetList(nn), nn);

Error in smi.SMLM/testFit (line 118)
        obj.analyzeAll(DatasetIndex);

```

**Comment by MJWester** [comment]
All the above have been done, that is, DIP is removed from smite here (and elsewhere), a TestFit directory is produced when running smi.SMLM.testFit, and the color overlay is written as an mp4 (although it has to be converted from a different format in Linux with an external program: ffmpeg since it cannot do it directly in Linux MATLAB).
